global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth:5000"]

  - job_name: "user"
    static_configs:
      - targets: ["user:5002"]

  - job_name: "job"
    static_configs:
      - targets: ["job:5003"]

  - job_name: "payment"
    static_configs:
      - targets: ["payment:5004"]

  - job_name: "utils"
    static_configs:
      - targets: ["utils:5001"]
